import win32com.client
speaker = win32com.client.Dispatch("SAPI.SpVoice")

#read text from text file generated by ocr
inFile=open('text.txt', "r")
text=inFile.read()

#speak out the text read
speaker.Speak(text)
#print(text)
#close file
inFile.close()
