import win32com.client
speaker = win32com.client.Dispatch("SAPI.SpVoice")

#read text from text file generated by ocr
inFile=open('text.txt', "r")
text=inFile.read()

#remove new line tags
text = text.replace('\n',' ')

#speak out the text read
speaker.Speak(text)

#print(text)
#close file
inFile.close()

'''
# importing the pyttsx library
import pyttsx3

# initialisation
engine = pyttsx3.init()

# testing
engine.say("My first code on text-to-speech")
engine.runAndWait()

'''